### ISSUE TITLE
[Question] About the chunk generation of modified XorShift+ PRNG used by cycle-crypt

### ISSUE THREAD

**Issue by phantomcraft** [duzun/cycle-crypt#9]
I have a doubt about the modified XorShift+ used by cycle-crypt.

Let's suppose a I use a 1MiB key forcing cycle-crypt to process 1MiB chunks. Will the PRNG emit the output continuously or need to process the entire output block before emitting? I mean, can the modified PRNG emit chunks shorter than the internal state filled by the key without the need of discarding the rest of the sequence before next cycle?

**Comment by duzun** [comment]
The block size (i.e. state size) is an internal detail, and should not be visible to the consumer of the API.
You get out as much data as you pipe in. Internal state keeps track of the "unused state" and continues using it on next data chunk. If the stream is closed, the last unused chunk of state is thrown away.

Regardless, I think there is a bug in the `stream.js` file. It is not related to the `cycle-crypt` algorithm though and does not affect the programmatic usage of this library, only the CLI.
 
But I see a different kind of problem when the key is longer then the data:
Not all the entropy of the key would be used! This is easily solvable by iterating at least two times during state generation
in [CycleCrypt.js](https://github.com/duzun/cycle-crypt/blob/master/CycleCrypt.js#L24) constructor. I wish the default number of rounds was 3, but unfortunately it is 1 in current implementation, and changing it to any other number would be a breaking change.
To solve this problem, I would make the number of rounds a parameter.

**Comment by duzun** [comment]
The bug is fixed in [9f06d0e](https://github.com/duzun/cycle-crypt/commit/9f06d0ef62e0e0b690a4f2ae1b7c4dbd5c9c3c0a)

**Comment by duzun** [comment]
Also added the [--salt-rounds|-sr](https://github.com/duzun/cycle-crypt/commit/3d1fcc912e5822b24e9ca8bb6f76e07413253643) argument to CLI.

**Comment by phantomcraft** [comment]
>If the stream is closed, the last unused chunk of state is thrown away.

Can the stream be closed before the chunk be computed? I mean, if I enter a 128-byte state, can I obtain only the half of the chunk (64-bytes) and discard the other half without computing it?

**Comment by duzun** [comment]
> With the previous version I was getting ~450MiB/s.

I don't see the difference between the before and after that commit:

![image](https://user-images.githubusercontent.com/321424/206879180-8bea08ea-0be7-446d-84d5-e9a0940f73c3.png)


That commit should fix an edge case, and should not influence the speed.

**Comment by duzun** [comment]
> Can the stream be closed before the chunk be computed? 

Not sure I fully understand your question.

There are three computations happening: 
1. The internal state is initially computed from key ⊕ salt,.
2. Then state is "advanced" when new data comes in to be encrypted. The advancement of the internal state is done in "blocks", i.e. from the old state the new state is computed in one go.
3. Next the data chunk is encrypted as state ^ chunk.

If the state is 128 bytes and the data chunk is 64 bytes, the state would be computed for 128 bytes, but only half of it would be used.

But it is possible to modify the algorithm so that it would calculate the sate in smaller chunks then the key-size, as data comes in.

**Comment by phantomcraft** [comment]
> > With the previous version I was getting ~450MiB/s.
> 
> I don't see the difference between the before and after that commit:
> 
> ![image](https://user-images.githubusercontent.com/321424/206879180-8bea08ea-0be7-446d-84d5-e9a0940f73c3.png)
> 
> That commit should fix an edge case, and should not influence the speed.

Sorry, it was the key size what was causing that slowdown:

```
user@localhost:~$ cat /dev/zero | cycle-crypt -k 0x"$(dd if=/dev/random count=16384 bs=1 2>/dev/null | xxd -p)" -s 0xaa | pv -pterb > /dev/null 
^C64GiB 0:00:17 [ 432MiB/s] [                                                <=>                                                                                              ]

user@localhost:~$ cat /dev/zero | cycle-crypt -k 0xaa -s 0xaa | pv -pterb > /dev/null 
^C96GiB 0:00:18 [ 149MiB/s] [      
```

**Comment by phantomcraft** [comment]
@duzun

Sorry, I don't know if it is my English or the native language way of speaking in English, but you understood what I meant.

I meant that, for example, calculate a 64-byte random data from the modified Xorshift+ used by cycle-crypt having the PRNG initialized with a 128-bytes key/state without having to output 128-bytes (and split into two 64-byte halves). 

> There are three computations happening:

> ...

Thanks for the explanation, now I better understand how Xorshift+ family of PRNGs work.

> If the state is 128 bytes and the data chunk is 64 bytes, the state would be computed for 128 bytes, but only half of it would be used.

Yep, I read about that in the cycle-crypt sources.

> But it is possible to modify the algorithm so that it would calculate the sate in smaller chunks then the key-size, as data comes in.

This answer my question; if it's possible I will study Xorshift+ and try to implement a modified version for smaller chunks.

**Comment by phantomcraft** [comment]
@duzun

> But it is possible to modify the algorithm so that it would calculate the sate in smaller chunks then the key-size, as data comes in.

In this hypothetical algorithm, could it be seeded with a 128-byte key, compute a 64-byte state and cycle the state after computing the 64-byte chunk? Would the chunks generated by this algorithm be fully dependent on the entropy of the key?

**Comment by duzun** [comment]
> Thanks for the explanation, now I better understand how Xorshift+ family of PRNGs work.

The three steps are specific to `cycle-crypt` encryption algorithm, not to XorShift+ PRNGs.

**Comment by duzun** [comment]
> In this hypothetical algorithm, could it be seeded with a 128-byte key, compute a 64-byte state and cycle the state after computing the 64-byte chunk? Would the chunks generated by this algorithm be fully dependent on the entropy of the key?

The state size could be another parameter to the algorithm, but I don't see much value in making it smaller or bigger then the key-size.

If you make it smaller then the key-size, during the init state stage all of the key bits should be used to generate the state, but naturally you loose some of the entropy in the general case. In other words, each bit of the key would influence the whole initial state, but for the same state there are many possible keys. What you actually lose is the size of the period of the resulted PRNG.

On the other hand, if you make the state bigger then the key, you inflate the entropy. If the seed is long enough, you earn artificial entropy for the state.

**Comment by phantomcraft** [comment]
@duzun 

I asked this because I'm thinking in a way to make a scheme based on cycle-crypt in which the stream is seekable, more specifically for disk encryption. 

It would be a good idea to have a fixed state (for disk encryption, 4096-bytes) and let the user specify the size of the key freely (maybe imposing a limit such as 32~40Kib). A fast and non-cryptographic hash function such as xxhash128 or cityhash128 could be used to map a numeric counter to a random string, and XOR the 128-bit mapped data into the key sequentially for each iteration. But after each iteration the resulting state of the key processing the state must be zeroed in order to be full-filled with the same key XORed with the mapped counter. Well, I don't know if you'll understand my idea, but I passed some hours thinking about that.

**Comment by phantomcraft** [comment]
Closing this issue, now I have the answer to the question, and also, it confirmed [here](https://crypto.stackexchange.com/questions/103205/can-i-emit-a-block-shorter-than-internal-state-of-any-xorshift-prng-without-ha).

For making a encryption scheme based on cycle-crypt that is seekable is not that hard.

Let's take the cycle-crypt PRNG, modify for emitting a defined size chunk and a fast hash function that runs fast on 32-bit host such as Blake2s.

1.  Find the position in the plaintext where data will be encrypted, it can be a 512/4096-byte block for disk sector encryption.
2.  Hash a counter (1, 2, 3, 4, 777, 888, 999...) with Blake2s with an internal hash key to form a 256-bits vector.
3.  XOR the output of hash function into the PRNG key repeating until all the key is modified. This will ensure that the emitted state of the PRNG will be depending on all bits of the counter.
4. Insert this modified temporary key in the PRNG and cycle it, producing a 512/4096-byte state.
5. XOR the state in the plaintext.
6. As the PRNG was cycled, reset the PRNG state to zero.
7. Repeat 1 to 6 for different position in the plaintext (the PRNG key is the same for all blocks).

The output of 32-bit hash function should be larger (256-bits) that the counter size (64/128-bits) for avoiding any collisions, and should be keyed to avoid any kind of ciphertext attack.

@duzun

Thanks for all the answers and explanations, when I learn C/C++ and feel competent I will create a cycle-crypt version in C for maximum performance.
